name: security_info_project
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  chewie: ^1.7.1
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  shaky_animated_listview: ^0.0.5
  shared_preferences: ^2.2.2
  video_player_web: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
    - assets/json/
    - .env
